// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_which_ColMins
IntegerVector C_which_ColMins(NumericMatrix X);
RcppExport SEXP _rowmins_C_which_ColMins(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_which_ColMins(X));
    return rcpp_result_gen;
END_RCPP
}
// C_which_rowMins
IntegerVector C_which_rowMins(NumericMatrix X);
RcppExport SEXP _rowmins_C_which_rowMins(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_which_rowMins(X));
    return rcpp_result_gen;
END_RCPP
}
// C_colMins
NumericVector C_colMins(NumericMatrix X);
RcppExport SEXP _rowmins_C_colMins(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_colMins(X));
    return rcpp_result_gen;
END_RCPP
}
// C_rowMins
NumericVector C_rowMins(NumericMatrix X);
RcppExport SEXP _rowmins_C_rowMins(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_rowMins(X));
    return rcpp_result_gen;
END_RCPP
}
// C_which_colMaxs
IntegerVector C_which_colMaxs(NumericMatrix X);
RcppExport SEXP _rowmins_C_which_colMaxs(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_which_colMaxs(X));
    return rcpp_result_gen;
END_RCPP
}
// C_which_rowMaxs
IntegerVector C_which_rowMaxs(NumericMatrix X);
RcppExport SEXP _rowmins_C_which_rowMaxs(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_which_rowMaxs(X));
    return rcpp_result_gen;
END_RCPP
}
// C_colMaxs
NumericVector C_colMaxs(NumericMatrix X);
RcppExport SEXP _rowmins_C_colMaxs(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_colMaxs(X));
    return rcpp_result_gen;
END_RCPP
}
// C_rowMaxs
NumericVector C_rowMaxs(NumericMatrix X);
RcppExport SEXP _rowmins_C_rowMaxs(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(C_rowMaxs(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rowmins_C_which_ColMins", (DL_FUNC) &_rowmins_C_which_ColMins, 1},
    {"_rowmins_C_which_rowMins", (DL_FUNC) &_rowmins_C_which_rowMins, 1},
    {"_rowmins_C_colMins", (DL_FUNC) &_rowmins_C_colMins, 1},
    {"_rowmins_C_rowMins", (DL_FUNC) &_rowmins_C_rowMins, 1},
    {"_rowmins_C_which_colMaxs", (DL_FUNC) &_rowmins_C_which_colMaxs, 1},
    {"_rowmins_C_which_rowMaxs", (DL_FUNC) &_rowmins_C_which_rowMaxs, 1},
    {"_rowmins_C_colMaxs", (DL_FUNC) &_rowmins_C_colMaxs, 1},
    {"_rowmins_C_rowMaxs", (DL_FUNC) &_rowmins_C_rowMaxs, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rowmins(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
