# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_which_ColMins <- function(X) {
    .Call(`_rowmins_C_which_ColMins`, X)
}

C_which_rowMins <- function(X) {
    .Call(`_rowmins_C_which_rowMins`, X)
}

C_colMins <- function(X) {
    .Call(`_rowmins_C_colMins`, X)
}

C_rowMins <- function(X) {
    .Call(`_rowmins_C_rowMins`, X)
}

C_which_colMaxs <- function(X) {
    .Call(`_rowmins_C_which_colMaxs`, X)
}

C_which_rowMaxs <- function(X) {
    .Call(`_rowmins_C_which_rowMaxs`, X)
}

C_colMaxs <- function(X) {
    .Call(`_rowmins_C_colMaxs`, X)
}

C_rowMaxs <- function(X) {
    .Call(`_rowmins_C_rowMaxs`, X)
}

