# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_which_colMins <- function(X) {
    .Call(`_rowmins_C_which_colMins`, X)
}

C_which_rowMins <- function(X) {
    .Call(`_rowmins_C_which_rowMins`, X)
}

#' Computes quickly the minima of each column of a matrix
#'
colMins <- function(X) {
    .Call(`_rowmins_colMins`, X)
}

#' Computes quickly the minima of each row of a matrix
#' 
rowMins <- function(X) {
    .Call(`_rowmins_rowMins`, X)
}

C_which_colMaxs <- function(X) {
    .Call(`_rowmins_C_which_colMaxs`, X)
}

C_which_rowMaxs <- function(X) {
    .Call(`_rowmins_C_which_rowMaxs`, X)
}

#' Computes quickly the maxima of each column of a matrix
#' 
colMaxs <- function(X) {
    .Call(`_rowmins_colMaxs`, X)
}

#' Computes quickly the maxima of each row of a matrix
#' 
rowMaxs <- function(X) {
    .Call(`_rowmins_rowMaxs`, X)
}

